spring.application.name=trading

spring.datasource.url=jdbc:postgresql://localhost:5432/onlineTrading
spring.datasource.username=postgres
spring.datasource.password=ABC123%%%

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect